name: build my angular app

on:
  push:
    branches: [ main ]

jobs:
  build-angular-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node JS
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        working-directory: "./Angular web/Angular-Build-Workflow"
        run: npm install

      - name: Build Angular App
        working-directory: "./Angular web/Angular-Build-Workflow"
        run: npm run build
